### PR TITLE
Share RecreateAllGroups Logic with CreateAnimeSeriesAndGroup

### PR DESCRIPTION
**Pull request by pmcleish**
- Updated AniDB_Anime.CreateAnimeSeriesAndGroup to use the same
  grouping logic as RecreateAllGroups.
- Updated AutoAnimeGroupCalculator to allow configuring what relation
  types use fuzzy title matching (Defaults to "secondary" relation
  types. e.g. Alternate setting, Other, etc).
- Added minimum air date strategy for selecting anime to use for group
  name and made it the default (Gives very similar results to the
  "weighted" approach I added, so probably no need to support it.
  Have left the strategy in just in case though).

I tested adding 10 new series that weren't in my database yet while auto grouping was enabled and they all went into the groups I was expecting them to. But, some further testing would still be needed of course.

Also, I think a server setting might be required to control the relationsToFuzzyTitleTest parameter of the AutoAnimeGroupCalculator (it could be added to the Create method in a similar way exclusions setting).
Either that or you could set it to whatever default is deemed best.

### CODE REVIEW

**Comment by da3dsoul** [comment]
Okay, I've found two issues.
1. JMM Desktop hangs perpetually after clicking the button @maxpiva we'll need input on that
2. Some filters (TvDB Links Missing is what I noticed) are filled with empty groups or groups that don't belong. I suspect it's an issue updating contracts as I have that filter set to the series level and it has empty results.

**Comment by da3dsoul** [comment]
Definitely a contract updating issue. My kodi contracts are fucked. The groups and series are there, but no info on anything. Banners and Fanarts, which are populated on request instead of by contract are the only working things.

**Comment by da3dsoul** [comment]
Contracts regenerated. I would have been upset, and then remember why when I go to watch something later.

**Comment by pmcleish** [comment]
@da3dsoul is there something I need look into? or has your recent commit fixed the contract issue?

**Comment by da3dsoul** [comment]
No I haven't fixed it. I've been fixing other bugs and keeping this branch updated.

**Comment by pmcleish** [comment]
ah ok, How do I go about seeing the problem? I assume I'll need to setup kodi (I've never used it)? since it was its contracts you mentioned? I don't think I touched kodi contract generation, so it they're not right, I must not be setting something up correctly before generating the contracts. I'll take a look once I know how to reproduce the issue.

**Comment by da3dsoul** [comment]
Setting up Kodi and testing would be the right way. The lazy way would be to use the master branch, Regen contracts, and call arbitrary XML and save them for comparison. http://localhost/JMMServerKodi/GetMetadata/1/0/9.XML is an example URL

**Comment by da3dsoul** [comment]
Specifically, look at Series.updatestats and Group.Updatefromtoplevel

**Comment by da3dsoul** [comment]
Those names aren't accurate, just enough to know what method

**Comment by da3dsoul** [comment]
Another way good way to check is to run a code coverage debug and check what is missing

**Comment by pmcleish** [comment]
That's a pretty good idea. I've checked the XML you mentioned and can certainly see there are issues. I'll setup Kodi tomorrow and start investigating.

**Pull request merged**
