### PR TITLE
Group recursively, group naming overhaul

### PR DESCRIPTION
**Pull request by da3dsoul**
git messed up the diff/whitespace again

### CODE REVIEW

**Comment by da3dsoul** [comment]
I'm learning how to use git/vs2015 (or vs at all). Cherry Picking is a great way to have a main personal dev branch and pull fixes into a PR.

**Comment by da3dsoul** [comment]
Don't merge this yet. I think there's something wrong with it.

**Comment by da3dsoul** [comment]
okay it's good now

**Comment by da3dsoul** [comment]
No it's not... There's an issue with renaming groups on import, and unfortunately merged groups have a chance of not keeping custom names. I can write a workaround, but it'll just pick one if there is more than one.

**Comment by da3dsoul** [comment]
It's good again. Will keep testing in the coming days to be sure.

**Comment by da3dsoul** [comment]
Before I forget to fix it after work. Rating on some series incorrect. When adding new shows, some are not grouped properly.

**Comment by da3dsoul** [comment]
The import seemed to work. I am grabbing a bunch of new stuff to test.

**Comment by da3dsoul** [comment]
Well, I just added 12 new shows, with 3-6 related parts each grouped and renamed properly. I'd say this is done, and if there are issues, someone can submit it.

**Comment by da3dsoul** [comment]
@maxpiva there will certainly be a few changes that need to be made to work with your new changes. Hopefully, they will all be minor changes. I know the update Stats will need to be repointed or removed, depending on how your system is written.

**Comment by da3dsoul** [comment]
@maxpiva I see it is much more involved to merge this to yours than I thought. I'm working on it difference by difference (I let it automerge the first time, but it became...not right)

**Comment by maxpiva** [comment]
Gonna check

**Comment by ElementalCrisis** [comment]
This PR is being rewritten and combined with https://github.com/japanesemediamanager/jmmserver/pull/257.

**Pull request closed without merging**
