### PR TITLE
Optimize Kodi XML sent over network

### PR DESCRIPTION
**Pull request by da3dsoul**
Also, provide cast info on the Season/Subgroup Level
And yes, Nakamori is already prepared for this commit... and tested...

### CODE REVIEW

**Comment by maxpiva** [comment]
Please use this in Contract_AniDB_Anime

 public List<Contract_AniDB_Character> Characters { get; set; }

Instead kodi Characters class, you can obtain the info needed from Contract_AniDB_Character instead.

**Comment by da3dsoul** [comment]
I'll take a look here shortly. Just woke up.

**Comment by da3dsoul** [comment]
Uh huh. I really don't know what I was thinking there. Hang on a sec.

**Comment by da3dsoul** [comment]
How's that @maxpiva?

**Comment by maxpiva** [comment]
Seems fine :)

**Comment by da3dsoul** [comment]
I really need to stop programming after being up for 20 hours...

**Comment by da3dsoul** [comment]
I'll fix this after get off work

**Comment by da3dsoul** [comment]
There we go

**Comment by maxpiva** [comment]
Already in the merged code.

**Pull request closed without merging**
