### PR TITLE
Cache and Db rework

### LINKED ISSUE #251: Groupfilters, cachestats and Anime Updates performance is subpar
On big collections, perfomance is subpar. Migrating the database to NOSQL and redo the whole system is a nono right now for me (No time).

So is time for plan B.

* groupfilter precalculations stored in DB.
* Optimize DB indices if possible.
* More intelligent approach to Anime Updates. (Recalculate less information).
* Stats Cache converted to a Group View Cache stored in the db, in a common format (class) that satisfy all clients.

### PR DESCRIPTION
**Pull request by maxpiva**
Pull seems stable enough. :)

This is a major change, backup your database before running. You can download this version from my jmmserver repo. Is running fine so far in my machine. But more test is needed, since it's a major rework.

* Major rework of the cache system, will fix #251, and also JMMServer will return data faster, for clients consumption, startup will be really fast right now, but Db needs generation, you should expect from 1 min to 3 hour startup (Depending of the size of your collection) only the first time (db generation), after that, startup will go down to a few seconds.

* Plex code is updated and more streamlined.

* Plex and Kodi support gzip compression of the results, if the client asked. (Plex ask for it).

* Plex support episode caching

* Plex and Kodi codebases merged.

### CODE REVIEW

**Comment by da3dsoul** [comment]
I noticed this wasn't merged in. Lots of fixes. https://github.com/japanesemediamanager/jmmserver/pull/253

**Comment by ElementalCrisis** [comment]
I believe @maxpiva is still working on this.

**Comment by maxpiva** [comment]
Nop finished

**Comment by maxpiva** [comment]
Done. Unable to test da3dsoul changes right now

**Comment by maxpiva** [comment]
Hold it. Seems da3dsoul merge, didn't go right

**Comment by maxpiva** [comment]
uff, now seems to be allright.

**Comment by da3dsoul** [comment]
Ah cool. And with most recent episode

**Comment by maxpiva** [comment]
I think is done, and release for beta testing. Warn users about db backup, just in case

**Pull request merged**
