### PR TITLE
Fix rating and tags for groups with multiple series for Kodi

### PR DESCRIPTION
**Pull request by da3dsoul**

### CODE REVIEW

**Comment by da3dsoul** [comment]
Fixes #250

**Comment by da3dsoul** [comment]
@bigretromike I'm gonna leave this open, as there is a part not included in yours (the Title of the PR)

**Comment by da3dsoul** [comment]
There's one more part I'm going to fix first, though. I noticed it on confluence. The year is not populated either, so I'll add it tonight (today, tomorrow, whatever time it is there...)

**Comment by bigretromike** [comment]
it is populating

**Comment by bigretromike** [comment]
ok by reverting it it is safe now ;-)

**Comment by bigretromike** [comment]
aaa

**Comment by da3dsoul** [comment]
I was referring to a group with multiple series in it.
screenie

**Comment by da3dsoul** [comment]
I just realized I had the op to ajin playing and it's in the screenie

**Comment by bigretromike** [comment]
Oh right, I turn that off when import collection once again.

**Comment by da3dsoul** [comment]
For things like .hack, macross, gundam, anything with 3 or more seasons, etc, it is really useful, which is why I've gone through such effort to make it work.

**Comment by da3dsoul** [comment]
I'm sure you've noticed I am very keen on aesthetics as well, so ever string needs to be formatted and presented neatly and concisely. Although, I realize some people don't like things exactly the way I do, so a settings list almost as long as the values they control is also a thing I do....

**Comment by da3dsoul** [comment]
This is officially ready for merge, I will not push anymore to it. Same with the last aired PRs

**Comment by ElementalCrisis** [comment]
Off-topic but have you joined our Discord server? It makes communicating much easier.

**Comment by da3dsoul** [comment]
What is discord

**Comment by da3dsoul** [comment]
Mk I now know what discord is.

**Comment by da3dsoul** [comment]
It would have been kind of github to notify me that this no longer builds against master...

**Comment by da3dsoul** [comment]
All better

**Pull request merged**
