### PR TITLE
Add Update Images Button

### PR DESCRIPTION
**Pull request by da3dsoul**
Also some small refactors for consistency. Scan Drop Folders on Import.

### CODE REVIEW

**Comment by ElementalCrisis** [comment]
Does this compare downloaded images against available images? Or does it overwrite your entire image folder re-downloading everything?

**Comment by da3dsoul** [comment]
It purely runs DownloadAllImages. I didn't trace the entire codepath to figure out all that it does. I figured it runs the importer to check to see if new images are available and downloads them if it has not reached the max images.

**Comment by da3dsoul** [comment]
I traced the codepath. It does exactly as I said above. It is there primarily for newly airing series that might not have all the images uploaded yet, or if you get banned and it destroys part of queue.

**Comment by da3dsoul** [comment]
Right, that happened

**Pull request closed without merging**
